name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "data/**"
      - "requirements.txt"
      - ".github/workflows/**"

jobs:
  run-predict:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the predict script
        run: |
          python src/predict.py "good"